name: vive_huanchaco
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

# --- 1. Firebase y Backend as a Service (BaaS) ---
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_messaging: ^15.2.7

# --- 2. Ubicación y Mapas ---
  google_maps_flutter: ^2.12.3
  google_places_flutter: ^2.1.0
  geolocator: ^14.0.1

# --- 3. Gestión de Estado y Arquitectura ---  
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3

# --- 4. Utilidades y UI/UX Complementarias ---
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.1
  http: ^1.4.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

assets:
  - assets/images/
  - assets/icons/

